### ISSUE TITLE
Does not work with Armatures created using Blender "Better FBX Importer and Exporter" Add-on

### ISSUE THREAD

**Issue by notMateo** [naelstrof/UnityJigglePhysics#8]
Title; doesn't function with armatures created using this blender addon. However, it does work perfectly fine with models created through Blender's built-in FBX exporter. 

The error given says "Can't have a singular bone with no parents. That doesn't even make sense!". After some digging, I noticed that the add-on exporter does NOT create child objects of the target bone. 

![image](https://user-images.githubusercontent.com/7546946/162633766-e5053f16-ccdf-4be6-9615-d8fcdfc903c2.png)
![image](https://user-images.githubusercontent.com/7546946/162633765-8c6e82a8-7496-4294-8f5a-7811f120b4f4.png)

Manually creating a child for the bone solves the issue, but I feel like, in this fringe case, some people may not discover that. I also emailed the developer of the Blender add-on about this issue. Maybe on this end, an option could be added to simulate/create a child bone for the jiggle rig to use?

Thanks, hope this helps, love this package!

**Comment by naelstrof** [comment]
Oh yup! That's an unintended consequence of our constraints, I'm surprised we haven't ran into that before.

Single bones can't be jiggled because our bone solve requires exactly two verlet points to calculate position and rotation. We can absolutely spawn a virtual bone for this case though. Thanks so much for the report! I'll submit a patch soon to fix it.

**Comment by naelstrof** [comment]
Should be fixed as of v3.4.3.

You can download it here: https://github.com/naelstrof/UnityJigglePhysics/releases/tag/v3.4.3

**Comment by notMateo** [comment]
Awesome! Honestly, super glad I could help and contribute just a bit here.
